### PR TITLE
Add init_from_hashmap to improve testability

### PR DESCRIPTION
**Pull request by danrspencer**
We've been using envconfig in our project for a while but have been tripping up with using it in tests where we may want to use the defaults, etc... from the config but don't want it pulling from environment variables. This change aims to address that by giving an alternative way to initialising the config struct for testing.

### CODE REVIEW

**Comment by greyblake** [comment]
@danrspencer What prevents you from initializing it in  the way you want?
E.g.
```rust
Config {
field1: 777,
field2: "foo".to_owned()?,
}
```

Or you can create your custom constructors.

**Comment by danrspencer** [comment]
Just initialising it doesn’t exercise the `envconfig` setting we’ve put in place. That has two main problems:

1. To verify you’ve correctly configured your struct via envconfig you currently have to set environment variables, e.g.

```
#[derive(Envconfig)]
pub struct Config {
    #[envconfig(from = "DB_HOST")]
    pub db_host: String,

    #[envconfig(from = "DB_PORT", default = "5432")]
    pub db_port: u16,
}

#[test]
fn it_errors_when_db_host_is_missing() {
   env::set_var("DB_HOST", "localhost");
   
   assert!(Config::init_from_env().is_err())
}
```

We really don’t want to be setting environment variables in our tests because, as you note in your own tests, without running in a single thread any tests setting environment variables are not isolated. 

With the new function I can assert in a unit test that I’ve correctly configured my envconfig struct.

```
#[test]
fn it_errors_when_db_host_is_missing() {
   let mut hashmap = HashMap::new()
   
   assert!(Config::init_from_hashmap(hashmap).is_err())
}
```

2. The second problem is that in integration tests we want to use most of the defaults we’ve setup in our envconfig. Currently this means either using real environment variables (which leads to nondeterministic tests so is a no) or we have to create the struct as you suggest and manually copy over all the defaults we’ve setup via envconfig. Then we have to keep anywhere we’ve manually created the struct up to date if we change any of the defaults. 

Being able to init from a hashmap means we can keep our integration tests isolated while still exercising the envconfig setup we’ve put in place.

**Comment by danrspencer** [comment]
Are you happy in principle with this PR? If it's just a matter of getting around to reviewing it properly, great. If not we'll have a look at moving to my fork directly.

**Comment by greyblake** [comment]
@danrspencer Sorry for the delay.
Yes, I think it's something I would consider accepting. Just need to find time to properly review it.

**Comment by greyblake** [comment]
@danrspencer Thanks again for the PR.
The change is available in the new version 0.10.0

**Comment by danrspencer** [comment]
Thanks for writing an extremely helpful config management utility! :)

**Pull request merged**
